spring.application.name=freelance_marketplace

spring.datasource.url=jdbc:mysql://localhost:3306/freelance_marketplace
spring.datasource.username=root
spring.datasource.password=Thuc123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phamnguyenminhthuc@gmail.com
spring.mail.password=thuc123456@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true