spring.application.name=freelance_marketplace

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.data.redis.host=freelance_marketplace_redis
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phamnguyenminhthuc@gmail.com
spring.mail.password=thuc123456@

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.elasticsearch.uris=http://localhost:9200

logging.level.org.springframework.data.elasticsearch.core=DEBUG
logging.level.co.elastic.clients.transport.Transport=TRACE


logging.level.co.elastic.clients.transport.rest_client=DEBUG
# 1. Ép Spring Boot dùng UTF-8 cho toàn bộ luồng Request/Response
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
spring.servlet.encoding.force-request=true


server.tomcat.uri-encoding=UTF-8

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_API_KEY}
cloudinary.api-secret=${CLOUD_API_SECRET}

stripe.api.secretKey=${STRIPE_API_KEY}
stripe.webhook.secret=${WEB_HOOK_SECRET}
